# Site settings
title: J 
email: 
description: "\"Above all, to watch. 
To try and understand.  
To never look away.  
And never, never to forget.\" 

- Arundhati Roy"
baseurl: ""
url: "www.jauzey.com"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty
