# Site settings
title: Jauzey
email: 
description: "To see with eyes unclouded by hate"
baseurl: ""
url: "www.jauzey.com"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty
collections: 
  quotes:
    output: true
  quran:
    output: true
