# Site settings
title: Jauzey 
email: jauzey.imam@gmail.com
description: "\"Above all, to watch. 
To try and understand.  
To never look away.  
And never, never to forget.\" 

- Arundhati Roy"
baseurl: ""
url: "www.jauzey.com"
twitter_username: jawziii
github_username:  jauzeyimam

# Build settings
markdown: kramdown
permalink: pretty
