# Site settings
title: Raw Critical Thoughts
email: 
description: "'Above all, to watch.<br>
To try and understand.<br>
To never look away.<br>
And never, never to forget.'<br>
--<br>
Arundhati Roy"
baseurl: ""
url: "www.jauzey.com"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty